
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


//whenever there is a connection to the server, the following message is getting printed
void message(){
    printf("New connection \n");
    }
   

   //in every function, argp connects the struct values to the program (pointing to the struct by using "->")
float *
average_1_svc(calculations *argp, struct svc_req *rqstp)
{
  
    message();

    static float  result;
       float temp = 0 ;
       for (int i = 0 ;  i < argp->size; i++){
        temp = temp + argp->array[i];
        }
        result = temp/argp->size;
        return &result;
  
}

calculations *
min_max_1_svc(calculations *argp, struct svc_req *rqstp)
{
    
    static calculations  result;
    float max = argp->array[0];
    float min = argp->array[0];
    result.minmax[0] = argp->array[0];
    
    for (int i = 0 ;  i < argp->size ; i++){
        if (argp->array[i] > max){
        max= argp->array[i];
        }
        if (argp->array[i]<min){
        min= argp->array[i];
        }
        result.minmax[0] = min;
        result.minmax[1] = max;
    }

    return &result;
}

calculations *
calc_a_y_1_svc(calculations *argp, struct svc_req *rqstp)
{    
    
    static calculations  result;
    
    for (int i = 0 ; i < argp->size; i++){
         argp->array[i] = argp->array[i]*argp->a;
    }
    for (int i = 0 ; i < argp->size ; i++){
        result.array[i] = argp->array[i];
    }
    return &result;
}
