/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host, float *array1, int size1, float a1, int choice1)
{
	CLIENT *clnt;
	float  *result_1;
	calculations  average_1_arg;
	calculations  *result_2;
	calculations  min_max_1_arg;
	calculations  *result_3;
	calculations  calc_a_y_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//perasma metavlhtwn apo thn main sta melh tou struct
	 average_1_arg.size = size1;
    	 min_max_1_arg.size = size1;
    	 calc_a_y_1_arg.size = size1;
	for (int i = 0 ; i < size1 ; i++){
	 average_1_arg.array[i] = array1[i];
	 min_max_1_arg.array[i] = array1[i];
	 calc_a_y_1_arg.array[i] = array1[i];
   	 }
    	 average_1_arg.choice = choice1;
    	 calc_a_y_1_arg.a = a1;
    	 
    	
    	 
    	 

	result_1 = average_1(&average_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = min_max_1(&min_max_1_arg, clnt);
	if (result_2 == (calculations *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = calc_a_y_1(&calc_a_y_1_arg, clnt);
	if (result_3 == (calculations *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	//elegxos gia poio choice dw8hke wste na paei ston swsto upologismo 
	 else{
        if (average_1_arg.choice ==1){

        printf("Average is : %f \n",*result_1);
        
        }
        else if (average_1_arg.choice ==2){
        printf("Min is %f and max is %f \n",result_2->minmax[0],result_2->minmax[1]);
        }
        else if (average_1_arg.choice==3){
        printf("The new array after the multiplication is : \n");
        	int temp;
        	for (int i = 0 ; i < size1 ; i++){
        	temp = i;
        		printf("Number %d element is %f \n" ,++temp,result_3->array[i]);
        	}
        }
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


/*h idea einai pws o xrhsths dinei apo to cmd to megethos tou pinaka, ta stoixeia tou pinaka  kai ton arithmo A. Ginontai me tous aparaithtous ypologismous wste to diavasma na einai apokleistika apo cmd */

int main(int argc, char *argv[])
{
 char *host;
 float *array_1,a1;
 int choice1;



 host = argv[1]; // to hostname
 a1 = atof(argv[2]); //to megethos a
 choice1 = atoi(argv[3]); // to choice gia to ti na upologisei
 // ta upoloipa einai ta stoixeia tou pinaka
 //prepei na exei sugkekrimeno format to input
 
 



  int size = argc -4;
  array_1=malloc(size*sizeof(float));
    if (array_1 == NULL) {
        printf("Memory allocation failed\n");
        exit(1);
    }
	a1 = atof(argv[2]);
  	choice1 = atoi(argv[3]);
  	for (int i = 0 ; i < size; i++){
 		array_1[i] = atof(argv[i+4]);
 	}
 calc_prog_1(host,array_1,size,a1,choice1);
 free(array_1);

	//Xrhsimopoiw diaforetiko array gia na mhn exw memory leak me to array1_1 mias kai ton exw xeiristei dunamika
	float array_2[100];
	int flag;
	size = 0;
	printf("Do you want to continue (1 yes / 0 no ) \n");
	scanf("%d",&flag);
	while (flag == 1){
		printf("Type the size : \n");
		scanf("%d",&size);
		printf("Type the value a and the choice \n");
		scanf("%f %d",&a1,&choice1);
		printf("Give the values of the array\n");
			for (int i = 0 ; i < size ; i++){
				scanf("%f",&array_2[i]);
			}
		calc_prog_1(host,array_2,size,a1,choice1);
		printf("Do you want to continue (1 yes / 0 no) \n");
		scanf("%d",&flag);
	}
printf("\n \n \n Exiting ... ");
exit (0);
}


